# Generated by Django 4.1.4 on 2023-01-02 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_delete_tag_alter_project_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
